apiVersion: v1
kind: Service
metadata:
  name:  wilmultd-rtp-service
  namespace: wilmultd
spec:
  type: NodePort
  selector:
    app: wilmultd-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000